### PR TITLE
added buttons to category pages

### PR DESCRIPTION
**Pull request by rachealcolbert**

### CODE REVIEW

**Review by AnnMarkham — CHANGES_REQUESTED** [review]
Merge conflict.  I think Amie added some stuff when she was trying to get the checkboxes to work at the same time that you were adding them back.

**Review by amiedawn — COMMENTED** [review]
I don't notice problems with this, except that we should be consistent with "your" dashboard, and "my" dashboard. The version I have on my computer still says 'My Dashboard' in the hero pic on the dashboard, but this header says "your dashboard." Just let us all know which one we are going with so we stay consistent. :)

**Comment by rachealcolbert** [comment]
Okay I believe I resolved the merge conflict.

**Comment by rachealcolbert** [comment]
Let's do My Dashboard.

**Review by AnnMarkham — APPROVED** [review]

**Pull request merged**
